# Generated by Django 5.2.1 on 2025-05-22 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Discount Percentage i.e.', max_digits=5),
        ),
        migrations.AddField(
            model_name='product',
            name='branch',
            field=models.ManyToManyField(to='store.branch'),
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
