# Generated by Django 5.2.1 on 2025-05-22 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_contact_created_at_contact_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
