# Generated by Django 5.2.1 on 2025-05-22 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_contact_alter_product_discount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
